# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GitHub Projects/216BProject/ECE216BNew.srcs/sources_1/bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_0/MEMDesign_blk_mem_gen_0_0.xci
# IP: The module: 'MEMDesign_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub Projects/216BProject/ECE216BNew.gen/sources_1/bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_0/MEMDesign_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEMDesign_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/GitHub Projects/216BProject/ECE216BNew.srcs/sources_1/bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_0/MEMDesign_blk_mem_gen_0_0.xci
# IP: The module: 'MEMDesign_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub Projects/216BProject/ECE216BNew.gen/sources_1/bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_0/MEMDesign_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEMDesign_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
