# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MEMDesign/MEMDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign || ORIG_REF_NAME==MEMDesign} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_0/MEMDesign_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_blk_mem_gen_0_0 || ORIG_REF_NAME==MEMDesign_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CADA_MEMControl_0_0/MEMDesign_CADA_MEMControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CADA_MEMControl_0_0 || ORIG_REF_NAME==MEMDesign_CADA_MEMControl_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_ArrayTop_0_0/MEMDesign_ArrayTop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_ArrayTop_0_0 || ORIG_REF_NAME==MEMDesign_ArrayTop_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CADA_LaneSplit_0_0/MEMDesign_CADA_LaneSplit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CADA_LaneSplit_0_0 || ORIG_REF_NAME==MEMDesign_CADA_LaneSplit_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_blk_mem_gen_0_1/MEMDesign_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_blk_mem_gen_0_1 || ORIG_REF_NAME==MEMDesign_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CADA_MEMControl_0_1/MEMDesign_CADA_MEMControl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CADA_MEMControl_0_1 || ORIG_REF_NAME==MEMDesign_CADA_MEMControl_0_1} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_mem_to_array_1_0_2/MEMDesign_mem_to_array_1_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_mem_to_array_1_0_2 || ORIG_REF_NAME==MEMDesign_mem_to_array_1_0_2} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_HA_1BM_0_0/MEMDesign_HA_1BM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_HA_1BM_0_0 || ORIG_REF_NAME==MEMDesign_HA_1BM_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_output_mapper_0_0/MEMDesign_output_mapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_output_mapper_0_0 || ORIG_REF_NAME==MEMDesign_output_mapper_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_HA_1BM_1_0/MEMDesign_HA_1BM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_HA_1BM_1_0 || ORIG_REF_NAME==MEMDesign_HA_1BM_1_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CADA_MEMControl_1_0/MEMDesign_CADA_MEMControl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CADA_MEMControl_1_0 || ORIG_REF_NAME==MEMDesign_CADA_MEMControl_1_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_blk_mem_gen_1_0/MEMDesign_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_blk_mem_gen_1_0 || ORIG_REF_NAME==MEMDesign_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_mem_to_array_2_0_0/MEMDesign_mem_to_array_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_mem_to_array_2_0_0 || ORIG_REF_NAME==MEMDesign_mem_to_array_2_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_HA_1BM_2_0/MEMDesign_HA_1BM_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_HA_1BM_2_0 || ORIG_REF_NAME==MEMDesign_HA_1BM_2_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_output_mapper_2_0_0/MEMDesign_output_mapper_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_output_mapper_2_0_0 || ORIG_REF_NAME==MEMDesign_output_mapper_2_0_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_LAYER_2_VALID_MUX_1/MEMDesign_LAYER_2_VALID_MUX_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_LAYER_2_VALID_MUX_1 || ORIG_REF_NAME==MEMDesign_LAYER_2_VALID_MUX_1} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_LAYER_2_INPUT_DATA_MEMCONTROL_0/MEMDesign_LAYER_2_INPUT_DATA_MEMCONTROL_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_LAYER_2_INPUT_DATA_MEMCONTROL_0 || ORIG_REF_NAME==MEMDesign_LAYER_2_INPUT_DATA_MEMCONTROL_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_LAYER_2_BLOCKRAM_0/MEMDesign_LAYER_2_BLOCKRAM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_LAYER_2_BLOCKRAM_0 || ORIG_REF_NAME==MEMDesign_LAYER_2_BLOCKRAM_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_HA_1BM_0_2/MEMDesign_HA_1BM_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_HA_1BM_0_2 || ORIG_REF_NAME==MEMDesign_HA_1BM_0_2} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CONFIG_BLOCKRAM_0/MEMDesign_CONFIG_BLOCKRAM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CONFIG_BLOCKRAM_0 || ORIG_REF_NAME==MEMDesign_CONFIG_BLOCKRAM_0} -quiet] -quiet

# IP: bd/MEMDesign/ip/MEMDesign_CONFIG_MEMCONTROL_0/MEMDesign_CONFIG_MEMCONTROL_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MEMDesign_CONFIG_MEMCONTROL_0 || ORIG_REF_NAME==MEMDesign_CONFIG_MEMCONTROL_0} -quiet] -quiet

# XDC: c:/Users/Keith/Documents/UCLA/216B/216BProject-keith_project_6_1/ECE216BNew.gen/sources_1/bd/MEMDesign/MEMDesign_ooc.xdc
